name: OpenAI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get diff
        id: diff
        run: echo "::set-output name=diff::$(git diff --name-only ${{ github.event.pull_request.head.sha }})"

      - name: Comment on diff
        uses: mshick/comment-on-diff-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          diff: ${{ steps.diff.outputs.diff }}
