name: OpenAI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Get Diff
        id: get-diff
        run: |
          # Get the diff between the base and head of the pull request
          diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=diff::$diff"

      - name: Run OpenAI Code Review
        id: run-openai-review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/openai_code_review.py "${{ steps.get-diff.outputs.diff }}"

      - name: Comment on Diff
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.run-openai-review.outputs.review_comments }}
          token: ${{ secrets.GITHUB_TOKEN }}
