name: Code Review with ChatGPT

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install openai

      - name: Generate Code Review Comments
        run: |
          # Fetch the pull request diff
          PR_DIFF=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})

          # Loop through each file in the diff and generate comments
          for file in $PR_DIFF; do
            # Fetch the file content
            FILE_CONTENT=$(cat $file)

            # Generate comment using OpenAI API
            COMMENT=$(curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
              -d '{"prompt": "Review the following code:\n'"$FILE_CONTENT"'", "temperature": 0.7}' \
              https://api.openai.com/v1/engines/davinci-codex/completions)

            # Add comment to the pull request
            gh pr review --body "$COMMENT" --comment "$COMMENT_ID" --approve
          done
